---
- include_role:
    name: webserver
    tasks_from: build_server
  loop: "{{ greet_names.split(';') | unique}}"
  vars:
    student_name: "{{ item }}"
    name_svc: "{{ item | lower | regex_replace(' ', '-') }}"
  loop_control:
    index_var: loop_idx
